//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ContosoDemoNAV.ApplicationTenant {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ApplicationTenant_Binding", Namespace="urn:microsoft-dynamics-schemas/page/applicationtenant")]
    public partial class ApplicationTenant_Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ReadOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadByRecIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadMultipleOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsUpdatedOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRecIdFromKeyOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateMultipleOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateMultipleOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteOperationCompleted;
        
        private System.Threading.SendOrPostCallback BeginProvisionOperationCompleted;
        
        private System.Threading.SendOrPostCallback BeginDeprovisionOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTenantUrlOperationCompleted;
        
        private System.Threading.SendOrPostCallback BeginMoveOperationCompleted;
        
        private System.Threading.SendOrPostCallback BeginCopyOperationCompleted;
        
        private System.Threading.SendOrPostCallback BeginPointInTimeCopyOperationCompleted;
        
        private System.Threading.SendOrPostCallback BeginBackUpOperationCompleted;
        
        private System.Threading.SendOrPostCallback BeginDeleteTenantAndDependentResourcesOperationCompleted;
        
        private System.Threading.SendOrPostCallback Delete_UsersOperationCompleted;
        
        private System.Threading.SendOrPostCallback Delete_App_Tenant_Subpage_CompaniesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ApplicationTenant_Service() {
            this.Url = global::ContosoDemoNAV.Properties.Settings.Default.ContosoDemoNAV_ApplicationTenant_ApplicationTenant_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ReadCompletedEventHandler ReadCompleted;
        
        /// <remarks/>
        public event ReadByRecIdCompletedEventHandler ReadByRecIdCompleted;
        
        /// <remarks/>
        public event ReadMultipleCompletedEventHandler ReadMultipleCompleted;
        
        /// <remarks/>
        public event IsUpdatedCompletedEventHandler IsUpdatedCompleted;
        
        /// <remarks/>
        public event GetRecIdFromKeyCompletedEventHandler GetRecIdFromKeyCompleted;
        
        /// <remarks/>
        public event CreateCompletedEventHandler CreateCompleted;
        
        /// <remarks/>
        public event CreateMultipleCompletedEventHandler CreateMultipleCompleted;
        
        /// <remarks/>
        public event UpdateCompletedEventHandler UpdateCompleted;
        
        /// <remarks/>
        public event UpdateMultipleCompletedEventHandler UpdateMultipleCompleted;
        
        /// <remarks/>
        public event DeleteCompletedEventHandler DeleteCompleted;
        
        /// <remarks/>
        public event BeginProvisionCompletedEventHandler BeginProvisionCompleted;
        
        /// <remarks/>
        public event BeginDeprovisionCompletedEventHandler BeginDeprovisionCompleted;
        
        /// <remarks/>
        public event GetTenantUrlCompletedEventHandler GetTenantUrlCompleted;
        
        /// <remarks/>
        public event BeginMoveCompletedEventHandler BeginMoveCompleted;
        
        /// <remarks/>
        public event BeginCopyCompletedEventHandler BeginCopyCompleted;
        
        /// <remarks/>
        public event BeginPointInTimeCopyCompletedEventHandler BeginPointInTimeCopyCompleted;
        
        /// <remarks/>
        public event BeginBackUpCompletedEventHandler BeginBackUpCompleted;
        
        /// <remarks/>
        public event BeginDeleteTenantAndDependentResourcesCompletedEventHandler BeginDeleteTenantAndDependentResourcesCompleted;
        
        /// <remarks/>
        public event Delete_UsersCompletedEventHandler Delete_UsersCompleted;
        
        /// <remarks/>
        public event Delete_App_Tenant_Subpage_CompaniesCompletedEventHandler Delete_App_Tenant_Subpage_CompaniesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/applicationtenant:Read", RequestNamespace="urn:microsoft-dynamics-schemas/page/applicationtenant", ResponseElementName="Read_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/applicationtenant", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ApplicationTenant")]
        public ApplicationTenant Read(string ID) {
            object[] results = this.Invoke("Read", new object[] {
                        ID});
            return ((ApplicationTenant)(results[0]));
        }
        
        /// <remarks/>
        public void ReadAsync(string ID) {
            this.ReadAsync(ID, null);
        }
        
        /// <remarks/>
        public void ReadAsync(string ID, object userState) {
            if ((this.ReadOperationCompleted == null)) {
                this.ReadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadOperationCompleted);
            }
            this.InvokeAsync("Read", new object[] {
                        ID}, this.ReadOperationCompleted, userState);
        }
        
        private void OnReadOperationCompleted(object arg) {
            if ((this.ReadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadCompleted(this, new ReadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/applicationtenant:ReadByRecId", RequestNamespace="urn:microsoft-dynamics-schemas/page/applicationtenant", ResponseElementName="ReadByRecId_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/applicationtenant", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("ApplicationTenant")]
        public ApplicationTenant ReadByRecId(string recId) {
            object[] results = this.Invoke("ReadByRecId", new object[] {
                        recId});
            return ((ApplicationTenant)(results[0]));
        }
        
        /// <remarks/>
        public void ReadByRecIdAsync(string recId) {
            this.ReadByRecIdAsync(recId, null);
        }
        
        /// <remarks/>
        public void ReadByRecIdAsync(string recId, object userState) {
            if ((this.ReadByRecIdOperationCompleted == null)) {
                this.ReadByRecIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadByRecIdOperationCompleted);
            }
            this.InvokeAsync("ReadByRecId", new object[] {
                        recId}, this.ReadByRecIdOperationCompleted, userState);
        }
        
        private void OnReadByRecIdOperationCompleted(object arg) {
            if ((this.ReadByRecIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadByRecIdCompleted(this, new ReadByRecIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/applicationtenant:ReadMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/applicationtenant", ResponseElementName="ReadMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/applicationtenant", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("ReadMultiple_Result")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ApplicationTenant[] ReadMultiple([System.Xml.Serialization.XmlElementAttribute("filter")] ApplicationTenant_Filter[] filter, string bookmarkKey, int setSize) {
            object[] results = this.Invoke("ReadMultiple", new object[] {
                        filter,
                        bookmarkKey,
                        setSize});
            return ((ApplicationTenant[])(results[0]));
        }
        
        /// <remarks/>
        public void ReadMultipleAsync(ApplicationTenant_Filter[] filter, string bookmarkKey, int setSize) {
            this.ReadMultipleAsync(filter, bookmarkKey, setSize, null);
        }
        
        /// <remarks/>
        public void ReadMultipleAsync(ApplicationTenant_Filter[] filter, string bookmarkKey, int setSize, object userState) {
            if ((this.ReadMultipleOperationCompleted == null)) {
                this.ReadMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadMultipleOperationCompleted);
            }
            this.InvokeAsync("ReadMultiple", new object[] {
                        filter,
                        bookmarkKey,
                        setSize}, this.ReadMultipleOperationCompleted, userState);
        }
        
        private void OnReadMultipleOperationCompleted(object arg) {
            if ((this.ReadMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadMultipleCompleted(this, new ReadMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/applicationtenant:IsUpdated", RequestNamespace="urn:microsoft-dynamics-schemas/page/applicationtenant", ResponseElementName="IsUpdated_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/applicationtenant", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("IsUpdated_Result")]
        public bool IsUpdated(string Key) {
            object[] results = this.Invoke("IsUpdated", new object[] {
                        Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsUpdatedAsync(string Key) {
            this.IsUpdatedAsync(Key, null);
        }
        
        /// <remarks/>
        public void IsUpdatedAsync(string Key, object userState) {
            if ((this.IsUpdatedOperationCompleted == null)) {
                this.IsUpdatedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsUpdatedOperationCompleted);
            }
            this.InvokeAsync("IsUpdated", new object[] {
                        Key}, this.IsUpdatedOperationCompleted, userState);
        }
        
        private void OnIsUpdatedOperationCompleted(object arg) {
            if ((this.IsUpdatedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsUpdatedCompleted(this, new IsUpdatedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/applicationtenant:GetRecIdFromKey", RequestNamespace="urn:microsoft-dynamics-schemas/page/applicationtenant", ResponseElementName="GetRecIdFromKey_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/applicationtenant", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetRecIdFromKey_Result")]
        public string GetRecIdFromKey(string Key) {
            object[] results = this.Invoke("GetRecIdFromKey", new object[] {
                        Key});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetRecIdFromKeyAsync(string Key) {
            this.GetRecIdFromKeyAsync(Key, null);
        }
        
        /// <remarks/>
        public void GetRecIdFromKeyAsync(string Key, object userState) {
            if ((this.GetRecIdFromKeyOperationCompleted == null)) {
                this.GetRecIdFromKeyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRecIdFromKeyOperationCompleted);
            }
            this.InvokeAsync("GetRecIdFromKey", new object[] {
                        Key}, this.GetRecIdFromKeyOperationCompleted, userState);
        }
        
        private void OnGetRecIdFromKeyOperationCompleted(object arg) {
            if ((this.GetRecIdFromKeyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRecIdFromKeyCompleted(this, new GetRecIdFromKeyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/applicationtenant:Create", RequestNamespace="urn:microsoft-dynamics-schemas/page/applicationtenant", ResponseElementName="Create_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/applicationtenant", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Create(ref ApplicationTenant ApplicationTenant) {
            object[] results = this.Invoke("Create", new object[] {
                        ApplicationTenant});
            ApplicationTenant = ((ApplicationTenant)(results[0]));
        }
        
        /// <remarks/>
        public void CreateAsync(ApplicationTenant ApplicationTenant) {
            this.CreateAsync(ApplicationTenant, null);
        }
        
        /// <remarks/>
        public void CreateAsync(ApplicationTenant ApplicationTenant, object userState) {
            if ((this.CreateOperationCompleted == null)) {
                this.CreateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateOperationCompleted);
            }
            this.InvokeAsync("Create", new object[] {
                        ApplicationTenant}, this.CreateOperationCompleted, userState);
        }
        
        private void OnCreateOperationCompleted(object arg) {
            if ((this.CreateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateCompleted(this, new CreateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/applicationtenant:CreateMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/applicationtenant", ResponseElementName="CreateMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/applicationtenant", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateMultiple([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] ref ApplicationTenant[] ApplicationTenant_List) {
            object[] results = this.Invoke("CreateMultiple", new object[] {
                        ApplicationTenant_List});
            ApplicationTenant_List = ((ApplicationTenant[])(results[0]));
        }
        
        /// <remarks/>
        public void CreateMultipleAsync(ApplicationTenant[] ApplicationTenant_List) {
            this.CreateMultipleAsync(ApplicationTenant_List, null);
        }
        
        /// <remarks/>
        public void CreateMultipleAsync(ApplicationTenant[] ApplicationTenant_List, object userState) {
            if ((this.CreateMultipleOperationCompleted == null)) {
                this.CreateMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateMultipleOperationCompleted);
            }
            this.InvokeAsync("CreateMultiple", new object[] {
                        ApplicationTenant_List}, this.CreateMultipleOperationCompleted, userState);
        }
        
        private void OnCreateMultipleOperationCompleted(object arg) {
            if ((this.CreateMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateMultipleCompleted(this, new CreateMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/applicationtenant:Update", RequestNamespace="urn:microsoft-dynamics-schemas/page/applicationtenant", ResponseElementName="Update_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/applicationtenant", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Update(ref ApplicationTenant ApplicationTenant) {
            object[] results = this.Invoke("Update", new object[] {
                        ApplicationTenant});
            ApplicationTenant = ((ApplicationTenant)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateAsync(ApplicationTenant ApplicationTenant) {
            this.UpdateAsync(ApplicationTenant, null);
        }
        
        /// <remarks/>
        public void UpdateAsync(ApplicationTenant ApplicationTenant, object userState) {
            if ((this.UpdateOperationCompleted == null)) {
                this.UpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateOperationCompleted);
            }
            this.InvokeAsync("Update", new object[] {
                        ApplicationTenant}, this.UpdateOperationCompleted, userState);
        }
        
        private void OnUpdateOperationCompleted(object arg) {
            if ((this.UpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCompleted(this, new UpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/applicationtenant:UpdateMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/applicationtenant", ResponseElementName="UpdateMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/applicationtenant", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateMultiple([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] ref ApplicationTenant[] ApplicationTenant_List) {
            object[] results = this.Invoke("UpdateMultiple", new object[] {
                        ApplicationTenant_List});
            ApplicationTenant_List = ((ApplicationTenant[])(results[0]));
        }
        
        /// <remarks/>
        public void UpdateMultipleAsync(ApplicationTenant[] ApplicationTenant_List) {
            this.UpdateMultipleAsync(ApplicationTenant_List, null);
        }
        
        /// <remarks/>
        public void UpdateMultipleAsync(ApplicationTenant[] ApplicationTenant_List, object userState) {
            if ((this.UpdateMultipleOperationCompleted == null)) {
                this.UpdateMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateMultipleOperationCompleted);
            }
            this.InvokeAsync("UpdateMultiple", new object[] {
                        ApplicationTenant_List}, this.UpdateMultipleOperationCompleted, userState);
        }
        
        private void OnUpdateMultipleOperationCompleted(object arg) {
            if ((this.UpdateMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateMultipleCompleted(this, new UpdateMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/applicationtenant:Delete", RequestNamespace="urn:microsoft-dynamics-schemas/page/applicationtenant", ResponseElementName="Delete_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/applicationtenant", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Delete_Result")]
        public bool Delete(string Key) {
            object[] results = this.Invoke("Delete", new object[] {
                        Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteAsync(string Key) {
            this.DeleteAsync(Key, null);
        }
        
        /// <remarks/>
        public void DeleteAsync(string Key, object userState) {
            if ((this.DeleteOperationCompleted == null)) {
                this.DeleteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteOperationCompleted);
            }
            this.InvokeAsync("Delete", new object[] {
                        Key}, this.DeleteOperationCompleted, userState);
        }
        
        private void OnDeleteOperationCompleted(object arg) {
            if ((this.DeleteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteCompleted(this, new DeleteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/applicationtenant:BeginProvision", RequestNamespace="urn:microsoft-dynamics-schemas/page/applicationtenant", ResponseElementName="BeginProvision_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/applicationtenant", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string BeginProvision(string applicationTenant) {
            object[] results = this.Invoke("BeginProvision", new object[] {
                        applicationTenant});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void BeginProvisionAsync(string applicationTenant) {
            this.BeginProvisionAsync(applicationTenant, null);
        }
        
        /// <remarks/>
        public void BeginProvisionAsync(string applicationTenant, object userState) {
            if ((this.BeginProvisionOperationCompleted == null)) {
                this.BeginProvisionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBeginProvisionOperationCompleted);
            }
            this.InvokeAsync("BeginProvision", new object[] {
                        applicationTenant}, this.BeginProvisionOperationCompleted, userState);
        }
        
        private void OnBeginProvisionOperationCompleted(object arg) {
            if ((this.BeginProvisionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BeginProvisionCompleted(this, new BeginProvisionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/applicationtenant:BeginDeprovision", RequestNamespace="urn:microsoft-dynamics-schemas/page/applicationtenant", ResponseElementName="BeginDeprovision_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/applicationtenant", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string BeginDeprovision(string applicationTenant) {
            object[] results = this.Invoke("BeginDeprovision", new object[] {
                        applicationTenant});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void BeginDeprovisionAsync(string applicationTenant) {
            this.BeginDeprovisionAsync(applicationTenant, null);
        }
        
        /// <remarks/>
        public void BeginDeprovisionAsync(string applicationTenant, object userState) {
            if ((this.BeginDeprovisionOperationCompleted == null)) {
                this.BeginDeprovisionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBeginDeprovisionOperationCompleted);
            }
            this.InvokeAsync("BeginDeprovision", new object[] {
                        applicationTenant}, this.BeginDeprovisionOperationCompleted, userState);
        }
        
        private void OnBeginDeprovisionOperationCompleted(object arg) {
            if ((this.BeginDeprovisionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BeginDeprovisionCompleted(this, new BeginDeprovisionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/applicationtenant:GetTenantUrl", RequestNamespace="urn:microsoft-dynamics-schemas/page/applicationtenant", ResponseElementName="GetTenantUrl_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/applicationtenant", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string GetTenantUrl(string applicationTenant) {
            object[] results = this.Invoke("GetTenantUrl", new object[] {
                        applicationTenant});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetTenantUrlAsync(string applicationTenant) {
            this.GetTenantUrlAsync(applicationTenant, null);
        }
        
        /// <remarks/>
        public void GetTenantUrlAsync(string applicationTenant, object userState) {
            if ((this.GetTenantUrlOperationCompleted == null)) {
                this.GetTenantUrlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTenantUrlOperationCompleted);
            }
            this.InvokeAsync("GetTenantUrl", new object[] {
                        applicationTenant}, this.GetTenantUrlOperationCompleted, userState);
        }
        
        private void OnGetTenantUrlOperationCompleted(object arg) {
            if ((this.GetTenantUrlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTenantUrlCompleted(this, new GetTenantUrlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/applicationtenant:BeginMove", RequestNamespace="urn:microsoft-dynamics-schemas/page/applicationtenant", ResponseElementName="BeginMove_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/applicationtenant", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string BeginMove(string applicationTenant, string destinationServiceName) {
            object[] results = this.Invoke("BeginMove", new object[] {
                        applicationTenant,
                        destinationServiceName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void BeginMoveAsync(string applicationTenant, string destinationServiceName) {
            this.BeginMoveAsync(applicationTenant, destinationServiceName, null);
        }
        
        /// <remarks/>
        public void BeginMoveAsync(string applicationTenant, string destinationServiceName, object userState) {
            if ((this.BeginMoveOperationCompleted == null)) {
                this.BeginMoveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBeginMoveOperationCompleted);
            }
            this.InvokeAsync("BeginMove", new object[] {
                        applicationTenant,
                        destinationServiceName}, this.BeginMoveOperationCompleted, userState);
        }
        
        private void OnBeginMoveOperationCompleted(object arg) {
            if ((this.BeginMoveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BeginMoveCompleted(this, new BeginMoveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/applicationtenant:BeginCopy", RequestNamespace="urn:microsoft-dynamics-schemas/page/applicationtenant", ResponseElementName="BeginCopy_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/applicationtenant", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string BeginCopy(string applicationTenant, string destinationServiceName, string copyName, string customSubdomainPrefix, bool allowAppDatabaseWrite) {
            object[] results = this.Invoke("BeginCopy", new object[] {
                        applicationTenant,
                        destinationServiceName,
                        copyName,
                        customSubdomainPrefix,
                        allowAppDatabaseWrite});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void BeginCopyAsync(string applicationTenant, string destinationServiceName, string copyName, string customSubdomainPrefix, bool allowAppDatabaseWrite) {
            this.BeginCopyAsync(applicationTenant, destinationServiceName, copyName, customSubdomainPrefix, allowAppDatabaseWrite, null);
        }
        
        /// <remarks/>
        public void BeginCopyAsync(string applicationTenant, string destinationServiceName, string copyName, string customSubdomainPrefix, bool allowAppDatabaseWrite, object userState) {
            if ((this.BeginCopyOperationCompleted == null)) {
                this.BeginCopyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBeginCopyOperationCompleted);
            }
            this.InvokeAsync("BeginCopy", new object[] {
                        applicationTenant,
                        destinationServiceName,
                        copyName,
                        customSubdomainPrefix,
                        allowAppDatabaseWrite}, this.BeginCopyOperationCompleted, userState);
        }
        
        private void OnBeginCopyOperationCompleted(object arg) {
            if ((this.BeginCopyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BeginCopyCompleted(this, new BeginCopyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/applicationtenant:BeginPointInTimeCopy", RequestNamespace="urn:microsoft-dynamics-schemas/page/applicationtenant", ResponseElementName="BeginPointInTimeCopy_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/applicationtenant", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string BeginPointInTimeCopy(string applicationTenant, string destinationServiceName, string copyName, string customSubdomainPrefix, bool allowAppDatabaseWrite, System.DateTime pointInTime) {
            object[] results = this.Invoke("BeginPointInTimeCopy", new object[] {
                        applicationTenant,
                        destinationServiceName,
                        copyName,
                        customSubdomainPrefix,
                        allowAppDatabaseWrite,
                        pointInTime});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void BeginPointInTimeCopyAsync(string applicationTenant, string destinationServiceName, string copyName, string customSubdomainPrefix, bool allowAppDatabaseWrite, System.DateTime pointInTime) {
            this.BeginPointInTimeCopyAsync(applicationTenant, destinationServiceName, copyName, customSubdomainPrefix, allowAppDatabaseWrite, pointInTime, null);
        }
        
        /// <remarks/>
        public void BeginPointInTimeCopyAsync(string applicationTenant, string destinationServiceName, string copyName, string customSubdomainPrefix, bool allowAppDatabaseWrite, System.DateTime pointInTime, object userState) {
            if ((this.BeginPointInTimeCopyOperationCompleted == null)) {
                this.BeginPointInTimeCopyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBeginPointInTimeCopyOperationCompleted);
            }
            this.InvokeAsync("BeginPointInTimeCopy", new object[] {
                        applicationTenant,
                        destinationServiceName,
                        copyName,
                        customSubdomainPrefix,
                        allowAppDatabaseWrite,
                        pointInTime}, this.BeginPointInTimeCopyOperationCompleted, userState);
        }
        
        private void OnBeginPointInTimeCopyOperationCompleted(object arg) {
            if ((this.BeginPointInTimeCopyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BeginPointInTimeCopyCompleted(this, new BeginPointInTimeCopyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/applicationtenant:BeginBackUp", RequestNamespace="urn:microsoft-dynamics-schemas/page/applicationtenant", ResponseElementName="BeginBackUp_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/applicationtenant", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string BeginBackUp(string applicationTenant) {
            object[] results = this.Invoke("BeginBackUp", new object[] {
                        applicationTenant});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void BeginBackUpAsync(string applicationTenant) {
            this.BeginBackUpAsync(applicationTenant, null);
        }
        
        /// <remarks/>
        public void BeginBackUpAsync(string applicationTenant, object userState) {
            if ((this.BeginBackUpOperationCompleted == null)) {
                this.BeginBackUpOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBeginBackUpOperationCompleted);
            }
            this.InvokeAsync("BeginBackUp", new object[] {
                        applicationTenant}, this.BeginBackUpOperationCompleted, userState);
        }
        
        private void OnBeginBackUpOperationCompleted(object arg) {
            if ((this.BeginBackUpCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BeginBackUpCompleted(this, new BeginBackUpCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/applicationtenant:BeginDeleteTenantAndDepende" +
            "ntResources", RequestNamespace="urn:microsoft-dynamics-schemas/page/applicationtenant", ResponseElementName="BeginDeleteTenantAndDependentResources_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/applicationtenant", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string BeginDeleteTenantAndDependentResources(string applicationTenant) {
            object[] results = this.Invoke("BeginDeleteTenantAndDependentResources", new object[] {
                        applicationTenant});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void BeginDeleteTenantAndDependentResourcesAsync(string applicationTenant) {
            this.BeginDeleteTenantAndDependentResourcesAsync(applicationTenant, null);
        }
        
        /// <remarks/>
        public void BeginDeleteTenantAndDependentResourcesAsync(string applicationTenant, object userState) {
            if ((this.BeginDeleteTenantAndDependentResourcesOperationCompleted == null)) {
                this.BeginDeleteTenantAndDependentResourcesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBeginDeleteTenantAndDependentResourcesOperationCompleted);
            }
            this.InvokeAsync("BeginDeleteTenantAndDependentResources", new object[] {
                        applicationTenant}, this.BeginDeleteTenantAndDependentResourcesOperationCompleted, userState);
        }
        
        private void OnBeginDeleteTenantAndDependentResourcesOperationCompleted(object arg) {
            if ((this.BeginDeleteTenantAndDependentResourcesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BeginDeleteTenantAndDependentResourcesCompleted(this, new BeginDeleteTenantAndDependentResourcesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/applicationtenant:Delete_Users", RequestNamespace="urn:microsoft-dynamics-schemas/page/applicationtenant", ResponseElementName="Delete_Users_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/applicationtenant", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Delete_Users_Result")]
        public bool Delete_Users(string Users_Key) {
            object[] results = this.Invoke("Delete_Users", new object[] {
                        Users_Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Delete_UsersAsync(string Users_Key) {
            this.Delete_UsersAsync(Users_Key, null);
        }
        
        /// <remarks/>
        public void Delete_UsersAsync(string Users_Key, object userState) {
            if ((this.Delete_UsersOperationCompleted == null)) {
                this.Delete_UsersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDelete_UsersOperationCompleted);
            }
            this.InvokeAsync("Delete_Users", new object[] {
                        Users_Key}, this.Delete_UsersOperationCompleted, userState);
        }
        
        private void OnDelete_UsersOperationCompleted(object arg) {
            if ((this.Delete_UsersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Delete_UsersCompleted(this, new Delete_UsersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/applicationtenant:Delete_App_Tenant_Subpage_C" +
            "ompanies", RequestNamespace="urn:microsoft-dynamics-schemas/page/applicationtenant", ResponseElementName="Delete_App_Tenant_Subpage_Companies_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/applicationtenant", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("Delete_App_Tenant_Subpage_Companies_Result")]
        public bool Delete_App_Tenant_Subpage_Companies(string App_Tenant_Subpage_Companies_Key) {
            object[] results = this.Invoke("Delete_App_Tenant_Subpage_Companies", new object[] {
                        App_Tenant_Subpage_Companies_Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Delete_App_Tenant_Subpage_CompaniesAsync(string App_Tenant_Subpage_Companies_Key) {
            this.Delete_App_Tenant_Subpage_CompaniesAsync(App_Tenant_Subpage_Companies_Key, null);
        }
        
        /// <remarks/>
        public void Delete_App_Tenant_Subpage_CompaniesAsync(string App_Tenant_Subpage_Companies_Key, object userState) {
            if ((this.Delete_App_Tenant_Subpage_CompaniesOperationCompleted == null)) {
                this.Delete_App_Tenant_Subpage_CompaniesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDelete_App_Tenant_Subpage_CompaniesOperationCompleted);
            }
            this.InvokeAsync("Delete_App_Tenant_Subpage_Companies", new object[] {
                        App_Tenant_Subpage_Companies_Key}, this.Delete_App_Tenant_Subpage_CompaniesOperationCompleted, userState);
        }
        
        private void OnDelete_App_Tenant_Subpage_CompaniesOperationCompleted(object arg) {
            if ((this.Delete_App_Tenant_Subpage_CompaniesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Delete_App_Tenant_Subpage_CompaniesCompleted(this, new Delete_App_Tenant_Subpage_CompaniesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/applicationtenant")]
    public partial class ApplicationTenant {
        
        private string keyField;
        
        private string applicationServiceNameField;
        
        private string nameField;
        
        private string countryField;
        
        private Provisioning_Status provisioning_StatusField;
        
        private bool provisioning_StatusFieldSpecified;
        
        private System.DateTime provisioned_OnField;
        
        private bool provisioned_OnFieldSpecified;
        
        private string tagField;
        
        private string application_Service_Name_Web_Service_Filter_FieldField;
        
        private Application_Service_Status application_Service_StatusField;
        
        private bool application_Service_StatusFieldSpecified;
        
        private string idField;
        
        private string applicationTenantDataFileNameField;
        
        private string subdomain_PrefixField;
        
        private string custom_Domain_NameField;
        
        private string default_Domain_NameField;
        
        private string uRLField;
        
        private bool allow_App_Database_WriteField;
        
        private bool allow_App_Database_WriteFieldSpecified;
        
        private string table_Connection_NameField;
        
        private App_Tenant_Subpage_Users[] usersField;
        
        private App_Tenant_Subpage_Companies[] app_Tenant_Subpage_CompaniesField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string ApplicationServiceName {
            get {
                return this.applicationServiceNameField;
            }
            set {
                this.applicationServiceNameField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public Provisioning_Status Provisioning_Status {
            get {
                return this.provisioning_StatusField;
            }
            set {
                this.provisioning_StatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Provisioning_StatusSpecified {
            get {
                return this.provisioning_StatusFieldSpecified;
            }
            set {
                this.provisioning_StatusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Provisioned_On {
            get {
                return this.provisioned_OnField;
            }
            set {
                this.provisioned_OnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Provisioned_OnSpecified {
            get {
                return this.provisioned_OnFieldSpecified;
            }
            set {
                this.provisioned_OnFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Tag {
            get {
                return this.tagField;
            }
            set {
                this.tagField = value;
            }
        }
        
        /// <remarks/>
        public string Application_Service_Name_Web_Service_Filter_Field {
            get {
                return this.application_Service_Name_Web_Service_Filter_FieldField;
            }
            set {
                this.application_Service_Name_Web_Service_Filter_FieldField = value;
            }
        }
        
        /// <remarks/>
        public Application_Service_Status Application_Service_Status {
            get {
                return this.application_Service_StatusField;
            }
            set {
                this.application_Service_StatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Application_Service_StatusSpecified {
            get {
                return this.application_Service_StatusFieldSpecified;
            }
            set {
                this.application_Service_StatusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string ApplicationTenantDataFileName {
            get {
                return this.applicationTenantDataFileNameField;
            }
            set {
                this.applicationTenantDataFileNameField = value;
            }
        }
        
        /// <remarks/>
        public string Subdomain_Prefix {
            get {
                return this.subdomain_PrefixField;
            }
            set {
                this.subdomain_PrefixField = value;
            }
        }
        
        /// <remarks/>
        public string Custom_Domain_Name {
            get {
                return this.custom_Domain_NameField;
            }
            set {
                this.custom_Domain_NameField = value;
            }
        }
        
        /// <remarks/>
        public string Default_Domain_Name {
            get {
                return this.default_Domain_NameField;
            }
            set {
                this.default_Domain_NameField = value;
            }
        }
        
        /// <remarks/>
        public string URL {
            get {
                return this.uRLField;
            }
            set {
                this.uRLField = value;
            }
        }
        
        /// <remarks/>
        public bool Allow_App_Database_Write {
            get {
                return this.allow_App_Database_WriteField;
            }
            set {
                this.allow_App_Database_WriteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Allow_App_Database_WriteSpecified {
            get {
                return this.allow_App_Database_WriteFieldSpecified;
            }
            set {
                this.allow_App_Database_WriteFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Table_Connection_Name {
            get {
                return this.table_Connection_NameField;
            }
            set {
                this.table_Connection_NameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public App_Tenant_Subpage_Users[] Users {
            get {
                return this.usersField;
            }
            set {
                this.usersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public App_Tenant_Subpage_Companies[] App_Tenant_Subpage_Companies {
            get {
                return this.app_Tenant_Subpage_CompaniesField;
            }
            set {
                this.app_Tenant_Subpage_CompaniesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/applicationtenant")]
    public enum Provisioning_Status {
        
        /// <remarks/>
        Draft,
        
        /// <remarks/>
        Provisioning,
        
        /// <remarks/>
        Active,
        
        /// <remarks/>
        Deprovisioning,
        
        /// <remarks/>
        Deprovisioned,
        
        /// <remarks/>
        Provisioning_Failed,
        
        /// <remarks/>
        Deprovisioning_Failed,
        
        /// <remarks/>
        Moving,
        
        /// <remarks/>
        Deleting,
        
        /// <remarks/>
        Stopping,
        
        /// <remarks/>
        Stopped,
        
        /// <remarks/>
        Starting,
        
        /// <remarks/>
        Deleting_Failed,
        
        /// <remarks/>
        Failed,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/applicationtenant")]
    public enum Application_Service_Status {
        
        /// <remarks/>
        Draft,
        
        /// <remarks/>
        Provisioning,
        
        /// <remarks/>
        Provisioning_Failed,
        
        /// <remarks/>
        Deprovisioning,
        
        /// <remarks/>
        Deprovisioned,
        
        /// <remarks/>
        Deprovisioning_Failed,
        
        /// <remarks/>
        Stopped,
        
        /// <remarks/>
        Running,
        
        /// <remarks/>
        Starting,
        
        /// <remarks/>
        Stopping,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/applicationtenant")]
    public partial class App_Tenant_Subpage_Users {
        
        private string keyField;
        
        private string user_NameField;
        
        private string full_NameField;
        
        private bool administratorField;
        
        private bool administratorFieldSpecified;
        
        private string authentication_EmailField;
        
        private string contact_EmailField;
        
        private License_Type license_TypeField;
        
        private bool license_TypeFieldSpecified;
        
        private Status statusField;
        
        private bool statusFieldSpecified;
        
        private int active_SessionsField;
        
        private bool active_SessionsFieldSpecified;
        
        private bool partner_UserField;
        
        private bool partner_UserFieldSpecified;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string User_Name {
            get {
                return this.user_NameField;
            }
            set {
                this.user_NameField = value;
            }
        }
        
        /// <remarks/>
        public string Full_Name {
            get {
                return this.full_NameField;
            }
            set {
                this.full_NameField = value;
            }
        }
        
        /// <remarks/>
        public bool Administrator {
            get {
                return this.administratorField;
            }
            set {
                this.administratorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AdministratorSpecified {
            get {
                return this.administratorFieldSpecified;
            }
            set {
                this.administratorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Authentication_Email {
            get {
                return this.authentication_EmailField;
            }
            set {
                this.authentication_EmailField = value;
            }
        }
        
        /// <remarks/>
        public string Contact_Email {
            get {
                return this.contact_EmailField;
            }
            set {
                this.contact_EmailField = value;
            }
        }
        
        /// <remarks/>
        public License_Type License_Type {
            get {
                return this.license_TypeField;
            }
            set {
                this.license_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool License_TypeSpecified {
            get {
                return this.license_TypeFieldSpecified;
            }
            set {
                this.license_TypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Status Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Active_Sessions {
            get {
                return this.active_SessionsField;
            }
            set {
                this.active_SessionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Active_SessionsSpecified {
            get {
                return this.active_SessionsFieldSpecified;
            }
            set {
                this.active_SessionsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Partner_User {
            get {
                return this.partner_UserField;
            }
            set {
                this.partner_UserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Partner_UserSpecified {
            get {
                return this.partner_UserFieldSpecified;
            }
            set {
                this.partner_UserFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/applicationtenant")]
    public enum License_Type {
        
        /// <remarks/>
        Full_User,
        
        /// <remarks/>
        Limited_User,
        
        /// <remarks/>
        Device_Only_User,
        
        /// <remarks/>
        Windows_Group,
        
        /// <remarks/>
        External_User,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/applicationtenant")]
    public enum Status {
        
        /// <remarks/>
        Enabled,
        
        /// <remarks/>
        Disabled,
        
        /// <remarks/>
        Draft,
        
        /// <remarks/>
        Provisioning,
        
        /// <remarks/>
        Provisioning_Failed,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/applicationtenant")]
    public partial class ApplicationTenant_Filter {
        
        private ApplicationTenant_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        public ApplicationTenant_Fields Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        public string Criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/applicationtenant")]
    public enum ApplicationTenant_Fields {
        
        /// <remarks/>
        ApplicationServiceName,
        
        /// <remarks/>
        Name,
        
        /// <remarks/>
        Country,
        
        /// <remarks/>
        Provisioning_Status,
        
        /// <remarks/>
        Provisioned_On,
        
        /// <remarks/>
        Tag,
        
        /// <remarks/>
        Application_Service_Name_Web_Service_Filter_Field,
        
        /// <remarks/>
        Application_Service_Status,
        
        /// <remarks/>
        ID,
        
        /// <remarks/>
        ApplicationTenantDataFileName,
        
        /// <remarks/>
        Subdomain_Prefix,
        
        /// <remarks/>
        Custom_Domain_Name,
        
        /// <remarks/>
        Default_Domain_Name,
        
        /// <remarks/>
        URL,
        
        /// <remarks/>
        Allow_App_Database_Write,
        
        /// <remarks/>
        Table_Connection_Name,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/applicationtenant")]
    public partial class App_Tenant_Subpage_Companies {
        
        private string keyField;
        
        private string nameField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void ReadCompletedEventHandler(object sender, ReadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ApplicationTenant Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ApplicationTenant)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void ReadByRecIdCompletedEventHandler(object sender, ReadByRecIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadByRecIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadByRecIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ApplicationTenant Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ApplicationTenant)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void ReadMultipleCompletedEventHandler(object sender, ReadMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ApplicationTenant[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ApplicationTenant[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void IsUpdatedCompletedEventHandler(object sender, IsUpdatedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsUpdatedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsUpdatedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetRecIdFromKeyCompletedEventHandler(object sender, GetRecIdFromKeyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRecIdFromKeyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRecIdFromKeyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void CreateCompletedEventHandler(object sender, CreateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ApplicationTenant ApplicationTenant {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ApplicationTenant)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void CreateMultipleCompletedEventHandler(object sender, CreateMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ApplicationTenant[] ApplicationTenant_List {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ApplicationTenant[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void UpdateCompletedEventHandler(object sender, UpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ApplicationTenant ApplicationTenant {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ApplicationTenant)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void UpdateMultipleCompletedEventHandler(object sender, UpdateMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ApplicationTenant[] ApplicationTenant_List {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ApplicationTenant[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void DeleteCompletedEventHandler(object sender, DeleteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void BeginProvisionCompletedEventHandler(object sender, BeginProvisionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BeginProvisionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BeginProvisionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void BeginDeprovisionCompletedEventHandler(object sender, BeginDeprovisionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BeginDeprovisionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BeginDeprovisionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetTenantUrlCompletedEventHandler(object sender, GetTenantUrlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTenantUrlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTenantUrlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void BeginMoveCompletedEventHandler(object sender, BeginMoveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BeginMoveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BeginMoveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void BeginCopyCompletedEventHandler(object sender, BeginCopyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BeginCopyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BeginCopyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void BeginPointInTimeCopyCompletedEventHandler(object sender, BeginPointInTimeCopyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BeginPointInTimeCopyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BeginPointInTimeCopyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void BeginBackUpCompletedEventHandler(object sender, BeginBackUpCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BeginBackUpCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BeginBackUpCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void BeginDeleteTenantAndDependentResourcesCompletedEventHandler(object sender, BeginDeleteTenantAndDependentResourcesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BeginDeleteTenantAndDependentResourcesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BeginDeleteTenantAndDependentResourcesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void Delete_UsersCompletedEventHandler(object sender, Delete_UsersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Delete_UsersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Delete_UsersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void Delete_App_Tenant_Subpage_CompaniesCompletedEventHandler(object sender, Delete_App_Tenant_Subpage_CompaniesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Delete_App_Tenant_Subpage_CompaniesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Delete_App_Tenant_Subpage_CompaniesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591