//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContosoDemoNAV.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://navmanagementportal.navcloudapptest.net:7047/NAV/WS/MVCompany/Page/Applic" +
            "ationTenant?tenant=mvp")]
        public string ContosoDemoNAV_ApplicationTenant_ApplicationTenant_Service {
            get {
                return ((string)(this["ContosoDemoNAV_ApplicationTenant_ApplicationTenant_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://navmanagementportal.navcloudapptest.net:7047/NAV/WS/MVCompany/Codeunit/Op" +
            "eration?tenant=mvp")]
        public string ContosoDemoNAV_Operation_Operation {
            get {
                return ((string)(this["ContosoDemoNAV_Operation_Operation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://navmanagementportal.navcloudapptest.net:7047/NAV/WS/MVCompany/Page/Applic" +
            "ationTenantUser?tenant=mvp")]
        public string ContosoDemoNAV_ApplicationTenantUser_ApplicationTenantUser_Service {
            get {
                return ((string)(this["ContosoDemoNAV_ApplicationTenantUser_ApplicationTenantUser_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://demo01-ljdp16.navcloudapptest.net:7047/NAV/WS/CRONUS%20International%20Lt" +
            "d./Page/CompanyInformation")]
        public string ContosoDemoNAV_Tenant_CompanyInformation_CompanyInformation_Service {
            get {
                return ((string)(this["ContosoDemoNAV_Tenant_CompanyInformation_CompanyInformation_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://autodep0117-main.navcloudapptest.net:7047/NAV/WS/Contoso/Page/Application" +
            "TenantCompany?tenant=partnertenant")]
        public string ContosoDemoNAV_ApplicationTenantCompany_ApplicationTenantCompany_Service {
            get {
                return ((string)(this["ContosoDemoNAV_ApplicationTenantCompany_ApplicationTenantCompany_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://managementtenant-v19m56.navcloudapptest.net:7047/NAV/WS/CRONUS%20Internat" +
            "ional%20Ltd./Page/User")]
        public string ContosoDemoNAV_Tenant_User_User_Service {
            get {
                return ((string)(this["ContosoDemoNAV_Tenant_User_User_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://managementtenant-v19m56.navcloudapptest.net:7047/NAV/WS/CRONUS%20Internat" +
            "ional%20Ltd./Page/GLSetup")]
        public string ContosoDemoNAV_Tenant_GLSetup_GLSetup_Service {
            get {
                return ((string)(this["ContosoDemoNAV_Tenant_GLSetup_GLSetup_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://managementtenant-v19m56.navcloudapptest.net:7047/NAV/WS/CRONUS%20Internat" +
            "ional%20Ltd./Page/UserPermissionSet")]
        public string ContosoDemoNAV_Tenant_UserPermissionSet_UserPermissionSet_Service {
            get {
                return ((string)(this["ContosoDemoNAV_Tenant_UserPermissionSet_UserPermissionSet_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://managementtenant-v19m56.navcloudapptest.net:7047/NAV/WS/CRONUS%20Internat" +
            "ional%20Ltd./Page/PermissionSet")]
        public string ContosoDemoNAV_Tenant_PermissionSet_PermissionSet_Service {
            get {
                return ((string)(this["ContosoDemoNAV_Tenant_PermissionSet_PermissionSet_Service"]));
            }
        }
    }
}
