//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ContosoDemoNAV.Tenant.GLSetup {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GLSetup_Binding", Namespace="urn:microsoft-dynamics-schemas/page/glsetup")]
    public partial class GLSetup_Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ReadByRecIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadMultipleOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsUpdatedOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetRecIdFromKeyOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateMultipleOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public GLSetup_Service() {
            this.Url = global::ContosoDemoNAV.Properties.Settings.Default.ContosoDemoNAV_Tenant_GLSetup_GLSetup_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ReadByRecIdCompletedEventHandler ReadByRecIdCompleted;
        
        /// <remarks/>
        public event ReadMultipleCompletedEventHandler ReadMultipleCompleted;
        
        /// <remarks/>
        public event IsUpdatedCompletedEventHandler IsUpdatedCompleted;
        
        /// <remarks/>
        public event GetRecIdFromKeyCompletedEventHandler GetRecIdFromKeyCompleted;
        
        /// <remarks/>
        public event UpdateCompletedEventHandler UpdateCompleted;
        
        /// <remarks/>
        public event UpdateMultipleCompletedEventHandler UpdateMultipleCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/glsetup:ReadByRecId", RequestNamespace="urn:microsoft-dynamics-schemas/page/glsetup", ResponseElementName="ReadByRecId_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/glsetup", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("GLSetup")]
        public GLSetup ReadByRecId(string recId) {
            object[] results = this.Invoke("ReadByRecId", new object[] {
                        recId});
            return ((GLSetup)(results[0]));
        }
        
        /// <remarks/>
        public void ReadByRecIdAsync(string recId) {
            this.ReadByRecIdAsync(recId, null);
        }
        
        /// <remarks/>
        public void ReadByRecIdAsync(string recId, object userState) {
            if ((this.ReadByRecIdOperationCompleted == null)) {
                this.ReadByRecIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadByRecIdOperationCompleted);
            }
            this.InvokeAsync("ReadByRecId", new object[] {
                        recId}, this.ReadByRecIdOperationCompleted, userState);
        }
        
        private void OnReadByRecIdOperationCompleted(object arg) {
            if ((this.ReadByRecIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadByRecIdCompleted(this, new ReadByRecIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/glsetup:ReadMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/glsetup", ResponseElementName="ReadMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/glsetup", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("ReadMultiple_Result")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public GLSetup[] ReadMultiple([System.Xml.Serialization.XmlElementAttribute("filter")] GLSetup_Filter[] filter, string bookmarkKey, int setSize) {
            object[] results = this.Invoke("ReadMultiple", new object[] {
                        filter,
                        bookmarkKey,
                        setSize});
            return ((GLSetup[])(results[0]));
        }
        
        /// <remarks/>
        public void ReadMultipleAsync(GLSetup_Filter[] filter, string bookmarkKey, int setSize) {
            this.ReadMultipleAsync(filter, bookmarkKey, setSize, null);
        }
        
        /// <remarks/>
        public void ReadMultipleAsync(GLSetup_Filter[] filter, string bookmarkKey, int setSize, object userState) {
            if ((this.ReadMultipleOperationCompleted == null)) {
                this.ReadMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadMultipleOperationCompleted);
            }
            this.InvokeAsync("ReadMultiple", new object[] {
                        filter,
                        bookmarkKey,
                        setSize}, this.ReadMultipleOperationCompleted, userState);
        }
        
        private void OnReadMultipleOperationCompleted(object arg) {
            if ((this.ReadMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadMultipleCompleted(this, new ReadMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/glsetup:IsUpdated", RequestNamespace="urn:microsoft-dynamics-schemas/page/glsetup", ResponseElementName="IsUpdated_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/glsetup", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("IsUpdated_Result")]
        public bool IsUpdated(string Key) {
            object[] results = this.Invoke("IsUpdated", new object[] {
                        Key});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void IsUpdatedAsync(string Key) {
            this.IsUpdatedAsync(Key, null);
        }
        
        /// <remarks/>
        public void IsUpdatedAsync(string Key, object userState) {
            if ((this.IsUpdatedOperationCompleted == null)) {
                this.IsUpdatedOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsUpdatedOperationCompleted);
            }
            this.InvokeAsync("IsUpdated", new object[] {
                        Key}, this.IsUpdatedOperationCompleted, userState);
        }
        
        private void OnIsUpdatedOperationCompleted(object arg) {
            if ((this.IsUpdatedCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsUpdatedCompleted(this, new IsUpdatedCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/glsetup:GetRecIdFromKey", RequestNamespace="urn:microsoft-dynamics-schemas/page/glsetup", ResponseElementName="GetRecIdFromKey_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/glsetup", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetRecIdFromKey_Result")]
        public string GetRecIdFromKey(string Key) {
            object[] results = this.Invoke("GetRecIdFromKey", new object[] {
                        Key});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetRecIdFromKeyAsync(string Key) {
            this.GetRecIdFromKeyAsync(Key, null);
        }
        
        /// <remarks/>
        public void GetRecIdFromKeyAsync(string Key, object userState) {
            if ((this.GetRecIdFromKeyOperationCompleted == null)) {
                this.GetRecIdFromKeyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetRecIdFromKeyOperationCompleted);
            }
            this.InvokeAsync("GetRecIdFromKey", new object[] {
                        Key}, this.GetRecIdFromKeyOperationCompleted, userState);
        }
        
        private void OnGetRecIdFromKeyOperationCompleted(object arg) {
            if ((this.GetRecIdFromKeyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetRecIdFromKeyCompleted(this, new GetRecIdFromKeyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/glsetup:Update", RequestNamespace="urn:microsoft-dynamics-schemas/page/glsetup", ResponseElementName="Update_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/glsetup", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Update(ref GLSetup GLSetup) {
            object[] results = this.Invoke("Update", new object[] {
                        GLSetup});
            GLSetup = ((GLSetup)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateAsync(GLSetup GLSetup) {
            this.UpdateAsync(GLSetup, null);
        }
        
        /// <remarks/>
        public void UpdateAsync(GLSetup GLSetup, object userState) {
            if ((this.UpdateOperationCompleted == null)) {
                this.UpdateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateOperationCompleted);
            }
            this.InvokeAsync("Update", new object[] {
                        GLSetup}, this.UpdateOperationCompleted, userState);
        }
        
        private void OnUpdateOperationCompleted(object arg) {
            if ((this.UpdateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCompleted(this, new UpdateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/page/glsetup:UpdateMultiple", RequestNamespace="urn:microsoft-dynamics-schemas/page/glsetup", ResponseElementName="UpdateMultiple_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/page/glsetup", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateMultiple([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] ref GLSetup[] GLSetup_List) {
            object[] results = this.Invoke("UpdateMultiple", new object[] {
                        GLSetup_List});
            GLSetup_List = ((GLSetup[])(results[0]));
        }
        
        /// <remarks/>
        public void UpdateMultipleAsync(GLSetup[] GLSetup_List) {
            this.UpdateMultipleAsync(GLSetup_List, null);
        }
        
        /// <remarks/>
        public void UpdateMultipleAsync(GLSetup[] GLSetup_List, object userState) {
            if ((this.UpdateMultipleOperationCompleted == null)) {
                this.UpdateMultipleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateMultipleOperationCompleted);
            }
            this.InvokeAsync("UpdateMultiple", new object[] {
                        GLSetup_List}, this.UpdateMultipleOperationCompleted, userState);
        }
        
        private void OnUpdateMultipleOperationCompleted(object arg) {
            if ((this.UpdateMultipleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateMultipleCompleted(this, new UpdateMultipleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/glsetup")]
    public partial class GLSetup {
        
        private string keyField;
        
        private System.DateTime allow_Posting_FromField;
        
        private bool allow_Posting_FromFieldSpecified;
        
        private System.DateTime allow_Posting_ToField;
        
        private bool allow_Posting_ToFieldSpecified;
        
        private bool register_TimeField;
        
        private bool register_TimeFieldSpecified;
        
        private Local_Address_Format local_Address_FormatField;
        
        private bool local_Address_FormatFieldSpecified;
        
        private Local_Cont_Addr_Format local_Cont_Addr_FormatField;
        
        private bool local_Cont_Addr_FormatFieldSpecified;
        
        private decimal inv_Rounding_Precision_LCYField;
        
        private bool inv_Rounding_Precision_LCYFieldSpecified;
        
        private Inv_Rounding_Type_LCY inv_Rounding_Type_LCYField;
        
        private bool inv_Rounding_Type_LCYFieldSpecified;
        
        private System.DateTime allow_G_L_Acc_Deletion_BeforeField;
        
        private bool allow_G_L_Acc_Deletion_BeforeFieldSpecified;
        
        private bool check_G_L_Account_UsageField;
        
        private bool check_G_L_Account_UsageFieldSpecified;
        
        private bool eMU_CurrencyField;
        
        private bool eMU_CurrencyFieldSpecified;
        
        private string lCY_CodeField;
        
        private bool pmt_Disc_Excl_VATField;
        
        private bool pmt_Disc_Excl_VATFieldSpecified;
        
        private bool adjust_for_Payment_DiscField;
        
        private bool adjust_for_Payment_DiscFieldSpecified;
        
        private bool unrealized_VATField;
        
        private bool unrealized_VATFieldSpecified;
        
        private bool prepayment_Unrealized_VATField;
        
        private bool prepayment_Unrealized_VATFieldSpecified;
        
        private decimal max_VAT_Difference_AllowedField;
        
        private bool max_VAT_Difference_AllowedFieldSpecified;
        
        private VAT_Rounding_Type vAT_Rounding_TypeField;
        
        private bool vAT_Rounding_TypeFieldSpecified;
        
        private Bill_to_Sell_to_VAT_Calc bill_to_Sell_to_VAT_CalcField;
        
        private bool bill_to_Sell_to_VAT_CalcFieldSpecified;
        
        private bool print_VAT_specification_in_LCYField;
        
        private bool print_VAT_specification_in_LCYFieldSpecified;
        
        private bool use_Legacy_G_L_Entry_LockingField;
        
        private bool use_Legacy_G_L_Entry_LockingFieldSpecified;
        
        private string bank_Account_NosField;
        
        private string global_Dimension_1_CodeField;
        
        private string global_Dimension_2_CodeField;
        
        private string shortcut_Dimension_1_CodeField;
        
        private string shortcut_Dimension_2_CodeField;
        
        private string shortcut_Dimension_3_CodeField;
        
        private string shortcut_Dimension_4_CodeField;
        
        private string shortcut_Dimension_5_CodeField;
        
        private string shortcut_Dimension_6_CodeField;
        
        private string shortcut_Dimension_7_CodeField;
        
        private string shortcut_Dimension_8_CodeField;
        
        private string additional_Reporting_CurrencyField;
        
        private VAT_Exchange_Rate_Adjustment vAT_Exchange_Rate_AdjustmentField;
        
        private bool vAT_Exchange_Rate_AdjustmentFieldSpecified;
        
        private string vAT_Reg_No_Validation_URLField;
        
        private decimal appln_Rounding_PrecisionField;
        
        private bool appln_Rounding_PrecisionFieldSpecified;
        
        private bool pmt_Disc_Tolerance_WarningField;
        
        private bool pmt_Disc_Tolerance_WarningFieldSpecified;
        
        private Pmt_Disc_Tolerance_Posting pmt_Disc_Tolerance_PostingField;
        
        private bool pmt_Disc_Tolerance_PostingFieldSpecified;
        
        private string payment_Discount_Grace_PeriodField;
        
        private bool payment_Tolerance_WarningField;
        
        private bool payment_Tolerance_WarningFieldSpecified;
        
        private Payment_Tolerance_Posting payment_Tolerance_PostingField;
        
        private bool payment_Tolerance_PostingFieldSpecified;
        
        private decimal payment_Tolerance_PercentField;
        
        private bool payment_Tolerance_PercentFieldSpecified;
        
        private decimal max_Payment_Tolerance_AmountField;
        
        private bool max_Payment_Tolerance_AmountFieldSpecified;
        
        private string payroll_Trans_Import_FormatField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Allow_Posting_From {
            get {
                return this.allow_Posting_FromField;
            }
            set {
                this.allow_Posting_FromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Allow_Posting_FromSpecified {
            get {
                return this.allow_Posting_FromFieldSpecified;
            }
            set {
                this.allow_Posting_FromFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Allow_Posting_To {
            get {
                return this.allow_Posting_ToField;
            }
            set {
                this.allow_Posting_ToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Allow_Posting_ToSpecified {
            get {
                return this.allow_Posting_ToFieldSpecified;
            }
            set {
                this.allow_Posting_ToFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Register_Time {
            get {
                return this.register_TimeField;
            }
            set {
                this.register_TimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Register_TimeSpecified {
            get {
                return this.register_TimeFieldSpecified;
            }
            set {
                this.register_TimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Local_Address_Format Local_Address_Format {
            get {
                return this.local_Address_FormatField;
            }
            set {
                this.local_Address_FormatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Local_Address_FormatSpecified {
            get {
                return this.local_Address_FormatFieldSpecified;
            }
            set {
                this.local_Address_FormatFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Local_Cont_Addr_Format Local_Cont_Addr_Format {
            get {
                return this.local_Cont_Addr_FormatField;
            }
            set {
                this.local_Cont_Addr_FormatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Local_Cont_Addr_FormatSpecified {
            get {
                return this.local_Cont_Addr_FormatFieldSpecified;
            }
            set {
                this.local_Cont_Addr_FormatFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Inv_Rounding_Precision_LCY {
            get {
                return this.inv_Rounding_Precision_LCYField;
            }
            set {
                this.inv_Rounding_Precision_LCYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Inv_Rounding_Precision_LCYSpecified {
            get {
                return this.inv_Rounding_Precision_LCYFieldSpecified;
            }
            set {
                this.inv_Rounding_Precision_LCYFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Inv_Rounding_Type_LCY Inv_Rounding_Type_LCY {
            get {
                return this.inv_Rounding_Type_LCYField;
            }
            set {
                this.inv_Rounding_Type_LCYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Inv_Rounding_Type_LCYSpecified {
            get {
                return this.inv_Rounding_Type_LCYFieldSpecified;
            }
            set {
                this.inv_Rounding_Type_LCYFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime Allow_G_L_Acc_Deletion_Before {
            get {
                return this.allow_G_L_Acc_Deletion_BeforeField;
            }
            set {
                this.allow_G_L_Acc_Deletion_BeforeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Allow_G_L_Acc_Deletion_BeforeSpecified {
            get {
                return this.allow_G_L_Acc_Deletion_BeforeFieldSpecified;
            }
            set {
                this.allow_G_L_Acc_Deletion_BeforeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Check_G_L_Account_Usage {
            get {
                return this.check_G_L_Account_UsageField;
            }
            set {
                this.check_G_L_Account_UsageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Check_G_L_Account_UsageSpecified {
            get {
                return this.check_G_L_Account_UsageFieldSpecified;
            }
            set {
                this.check_G_L_Account_UsageFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool EMU_Currency {
            get {
                return this.eMU_CurrencyField;
            }
            set {
                this.eMU_CurrencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EMU_CurrencySpecified {
            get {
                return this.eMU_CurrencyFieldSpecified;
            }
            set {
                this.eMU_CurrencyFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string LCY_Code {
            get {
                return this.lCY_CodeField;
            }
            set {
                this.lCY_CodeField = value;
            }
        }
        
        /// <remarks/>
        public bool Pmt_Disc_Excl_VAT {
            get {
                return this.pmt_Disc_Excl_VATField;
            }
            set {
                this.pmt_Disc_Excl_VATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Pmt_Disc_Excl_VATSpecified {
            get {
                return this.pmt_Disc_Excl_VATFieldSpecified;
            }
            set {
                this.pmt_Disc_Excl_VATFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Adjust_for_Payment_Disc {
            get {
                return this.adjust_for_Payment_DiscField;
            }
            set {
                this.adjust_for_Payment_DiscField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Adjust_for_Payment_DiscSpecified {
            get {
                return this.adjust_for_Payment_DiscFieldSpecified;
            }
            set {
                this.adjust_for_Payment_DiscFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Unrealized_VAT {
            get {
                return this.unrealized_VATField;
            }
            set {
                this.unrealized_VATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Unrealized_VATSpecified {
            get {
                return this.unrealized_VATFieldSpecified;
            }
            set {
                this.unrealized_VATFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Prepayment_Unrealized_VAT {
            get {
                return this.prepayment_Unrealized_VATField;
            }
            set {
                this.prepayment_Unrealized_VATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Prepayment_Unrealized_VATSpecified {
            get {
                return this.prepayment_Unrealized_VATFieldSpecified;
            }
            set {
                this.prepayment_Unrealized_VATFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Max_VAT_Difference_Allowed {
            get {
                return this.max_VAT_Difference_AllowedField;
            }
            set {
                this.max_VAT_Difference_AllowedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Max_VAT_Difference_AllowedSpecified {
            get {
                return this.max_VAT_Difference_AllowedFieldSpecified;
            }
            set {
                this.max_VAT_Difference_AllowedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public VAT_Rounding_Type VAT_Rounding_Type {
            get {
                return this.vAT_Rounding_TypeField;
            }
            set {
                this.vAT_Rounding_TypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VAT_Rounding_TypeSpecified {
            get {
                return this.vAT_Rounding_TypeFieldSpecified;
            }
            set {
                this.vAT_Rounding_TypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Bill_to_Sell_to_VAT_Calc Bill_to_Sell_to_VAT_Calc {
            get {
                return this.bill_to_Sell_to_VAT_CalcField;
            }
            set {
                this.bill_to_Sell_to_VAT_CalcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Bill_to_Sell_to_VAT_CalcSpecified {
            get {
                return this.bill_to_Sell_to_VAT_CalcFieldSpecified;
            }
            set {
                this.bill_to_Sell_to_VAT_CalcFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Print_VAT_specification_in_LCY {
            get {
                return this.print_VAT_specification_in_LCYField;
            }
            set {
                this.print_VAT_specification_in_LCYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Print_VAT_specification_in_LCYSpecified {
            get {
                return this.print_VAT_specification_in_LCYFieldSpecified;
            }
            set {
                this.print_VAT_specification_in_LCYFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Use_Legacy_G_L_Entry_Locking {
            get {
                return this.use_Legacy_G_L_Entry_LockingField;
            }
            set {
                this.use_Legacy_G_L_Entry_LockingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Use_Legacy_G_L_Entry_LockingSpecified {
            get {
                return this.use_Legacy_G_L_Entry_LockingFieldSpecified;
            }
            set {
                this.use_Legacy_G_L_Entry_LockingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Bank_Account_Nos {
            get {
                return this.bank_Account_NosField;
            }
            set {
                this.bank_Account_NosField = value;
            }
        }
        
        /// <remarks/>
        public string Global_Dimension_1_Code {
            get {
                return this.global_Dimension_1_CodeField;
            }
            set {
                this.global_Dimension_1_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Global_Dimension_2_Code {
            get {
                return this.global_Dimension_2_CodeField;
            }
            set {
                this.global_Dimension_2_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Shortcut_Dimension_1_Code {
            get {
                return this.shortcut_Dimension_1_CodeField;
            }
            set {
                this.shortcut_Dimension_1_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Shortcut_Dimension_2_Code {
            get {
                return this.shortcut_Dimension_2_CodeField;
            }
            set {
                this.shortcut_Dimension_2_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Shortcut_Dimension_3_Code {
            get {
                return this.shortcut_Dimension_3_CodeField;
            }
            set {
                this.shortcut_Dimension_3_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Shortcut_Dimension_4_Code {
            get {
                return this.shortcut_Dimension_4_CodeField;
            }
            set {
                this.shortcut_Dimension_4_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Shortcut_Dimension_5_Code {
            get {
                return this.shortcut_Dimension_5_CodeField;
            }
            set {
                this.shortcut_Dimension_5_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Shortcut_Dimension_6_Code {
            get {
                return this.shortcut_Dimension_6_CodeField;
            }
            set {
                this.shortcut_Dimension_6_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Shortcut_Dimension_7_Code {
            get {
                return this.shortcut_Dimension_7_CodeField;
            }
            set {
                this.shortcut_Dimension_7_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Shortcut_Dimension_8_Code {
            get {
                return this.shortcut_Dimension_8_CodeField;
            }
            set {
                this.shortcut_Dimension_8_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string Additional_Reporting_Currency {
            get {
                return this.additional_Reporting_CurrencyField;
            }
            set {
                this.additional_Reporting_CurrencyField = value;
            }
        }
        
        /// <remarks/>
        public VAT_Exchange_Rate_Adjustment VAT_Exchange_Rate_Adjustment {
            get {
                return this.vAT_Exchange_Rate_AdjustmentField;
            }
            set {
                this.vAT_Exchange_Rate_AdjustmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VAT_Exchange_Rate_AdjustmentSpecified {
            get {
                return this.vAT_Exchange_Rate_AdjustmentFieldSpecified;
            }
            set {
                this.vAT_Exchange_Rate_AdjustmentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string VAT_Reg_No_Validation_URL {
            get {
                return this.vAT_Reg_No_Validation_URLField;
            }
            set {
                this.vAT_Reg_No_Validation_URLField = value;
            }
        }
        
        /// <remarks/>
        public decimal Appln_Rounding_Precision {
            get {
                return this.appln_Rounding_PrecisionField;
            }
            set {
                this.appln_Rounding_PrecisionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Appln_Rounding_PrecisionSpecified {
            get {
                return this.appln_Rounding_PrecisionFieldSpecified;
            }
            set {
                this.appln_Rounding_PrecisionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool Pmt_Disc_Tolerance_Warning {
            get {
                return this.pmt_Disc_Tolerance_WarningField;
            }
            set {
                this.pmt_Disc_Tolerance_WarningField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Pmt_Disc_Tolerance_WarningSpecified {
            get {
                return this.pmt_Disc_Tolerance_WarningFieldSpecified;
            }
            set {
                this.pmt_Disc_Tolerance_WarningFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Pmt_Disc_Tolerance_Posting Pmt_Disc_Tolerance_Posting {
            get {
                return this.pmt_Disc_Tolerance_PostingField;
            }
            set {
                this.pmt_Disc_Tolerance_PostingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Pmt_Disc_Tolerance_PostingSpecified {
            get {
                return this.pmt_Disc_Tolerance_PostingFieldSpecified;
            }
            set {
                this.pmt_Disc_Tolerance_PostingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Payment_Discount_Grace_Period {
            get {
                return this.payment_Discount_Grace_PeriodField;
            }
            set {
                this.payment_Discount_Grace_PeriodField = value;
            }
        }
        
        /// <remarks/>
        public bool Payment_Tolerance_Warning {
            get {
                return this.payment_Tolerance_WarningField;
            }
            set {
                this.payment_Tolerance_WarningField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Payment_Tolerance_WarningSpecified {
            get {
                return this.payment_Tolerance_WarningFieldSpecified;
            }
            set {
                this.payment_Tolerance_WarningFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public Payment_Tolerance_Posting Payment_Tolerance_Posting {
            get {
                return this.payment_Tolerance_PostingField;
            }
            set {
                this.payment_Tolerance_PostingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Payment_Tolerance_PostingSpecified {
            get {
                return this.payment_Tolerance_PostingFieldSpecified;
            }
            set {
                this.payment_Tolerance_PostingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Payment_Tolerance_Percent {
            get {
                return this.payment_Tolerance_PercentField;
            }
            set {
                this.payment_Tolerance_PercentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Payment_Tolerance_PercentSpecified {
            get {
                return this.payment_Tolerance_PercentFieldSpecified;
            }
            set {
                this.payment_Tolerance_PercentFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal Max_Payment_Tolerance_Amount {
            get {
                return this.max_Payment_Tolerance_AmountField;
            }
            set {
                this.max_Payment_Tolerance_AmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Max_Payment_Tolerance_AmountSpecified {
            get {
                return this.max_Payment_Tolerance_AmountFieldSpecified;
            }
            set {
                this.max_Payment_Tolerance_AmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string Payroll_Trans_Import_Format {
            get {
                return this.payroll_Trans_Import_FormatField;
            }
            set {
                this.payroll_Trans_Import_FormatField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/glsetup")]
    public enum Local_Address_Format {
        
        /// <remarks/>
        Post_Code_x002B_City,
        
        /// <remarks/>
        City_x002B_Post_Code,
        
        /// <remarks/>
        City_x002B_County_x002B_Post_Code,
        
        /// <remarks/>
        Blank_Line_x002B_Post_Code_x002B_City,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/glsetup")]
    public enum Local_Cont_Addr_Format {
        
        /// <remarks/>
        First,
        
        /// <remarks/>
        After_Company_Name,
        
        /// <remarks/>
        Last,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/glsetup")]
    public enum Inv_Rounding_Type_LCY {
        
        /// <remarks/>
        Nearest,
        
        /// <remarks/>
        Up,
        
        /// <remarks/>
        Down,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/glsetup")]
    public enum VAT_Rounding_Type {
        
        /// <remarks/>
        Nearest,
        
        /// <remarks/>
        Up,
        
        /// <remarks/>
        Down,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/glsetup")]
    public enum Bill_to_Sell_to_VAT_Calc {
        
        /// <remarks/>
        Bill_to_Pay_to_No,
        
        /// <remarks/>
        Sell_to_Buy_from_No,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/glsetup")]
    public enum VAT_Exchange_Rate_Adjustment {
        
        /// <remarks/>
        No_Adjustment,
        
        /// <remarks/>
        Adjust_Amount,
        
        /// <remarks/>
        Adjust_Additional_Currency_Amount,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/glsetup")]
    public enum Pmt_Disc_Tolerance_Posting {
        
        /// <remarks/>
        Payment_Tolerance_Accounts,
        
        /// <remarks/>
        Payment_Discount_Accounts,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/glsetup")]
    public enum Payment_Tolerance_Posting {
        
        /// <remarks/>
        Payment_Tolerance_Accounts,
        
        /// <remarks/>
        Payment_Discount_Accounts,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/glsetup")]
    public partial class GLSetup_Filter {
        
        private GLSetup_Fields fieldField;
        
        private string criteriaField;
        
        /// <remarks/>
        public GLSetup_Fields Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        public string Criteria {
            get {
                return this.criteriaField;
            }
            set {
                this.criteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1038.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:microsoft-dynamics-schemas/page/glsetup")]
    public enum GLSetup_Fields {
        
        /// <remarks/>
        Allow_Posting_From,
        
        /// <remarks/>
        Allow_Posting_To,
        
        /// <remarks/>
        Register_Time,
        
        /// <remarks/>
        Local_Address_Format,
        
        /// <remarks/>
        Local_Cont_Addr_Format,
        
        /// <remarks/>
        Inv_Rounding_Precision_LCY,
        
        /// <remarks/>
        Inv_Rounding_Type_LCY,
        
        /// <remarks/>
        Allow_G_L_Acc_Deletion_Before,
        
        /// <remarks/>
        Check_G_L_Account_Usage,
        
        /// <remarks/>
        EMU_Currency,
        
        /// <remarks/>
        LCY_Code,
        
        /// <remarks/>
        Pmt_Disc_Excl_VAT,
        
        /// <remarks/>
        Adjust_for_Payment_Disc,
        
        /// <remarks/>
        Unrealized_VAT,
        
        /// <remarks/>
        Prepayment_Unrealized_VAT,
        
        /// <remarks/>
        Max_VAT_Difference_Allowed,
        
        /// <remarks/>
        VAT_Rounding_Type,
        
        /// <remarks/>
        Bill_to_Sell_to_VAT_Calc,
        
        /// <remarks/>
        Print_VAT_specification_in_LCY,
        
        /// <remarks/>
        Use_Legacy_G_L_Entry_Locking,
        
        /// <remarks/>
        Bank_Account_Nos,
        
        /// <remarks/>
        Global_Dimension_1_Code,
        
        /// <remarks/>
        Global_Dimension_2_Code,
        
        /// <remarks/>
        Shortcut_Dimension_1_Code,
        
        /// <remarks/>
        Shortcut_Dimension_2_Code,
        
        /// <remarks/>
        Shortcut_Dimension_3_Code,
        
        /// <remarks/>
        Shortcut_Dimension_4_Code,
        
        /// <remarks/>
        Shortcut_Dimension_5_Code,
        
        /// <remarks/>
        Shortcut_Dimension_6_Code,
        
        /// <remarks/>
        Shortcut_Dimension_7_Code,
        
        /// <remarks/>
        Shortcut_Dimension_8_Code,
        
        /// <remarks/>
        Additional_Reporting_Currency,
        
        /// <remarks/>
        VAT_Exchange_Rate_Adjustment,
        
        /// <remarks/>
        VAT_Reg_No_Validation_URL,
        
        /// <remarks/>
        Appln_Rounding_Precision,
        
        /// <remarks/>
        Pmt_Disc_Tolerance_Warning,
        
        /// <remarks/>
        Pmt_Disc_Tolerance_Posting,
        
        /// <remarks/>
        Payment_Discount_Grace_Period,
        
        /// <remarks/>
        Payment_Tolerance_Warning,
        
        /// <remarks/>
        Payment_Tolerance_Posting,
        
        /// <remarks/>
        Payment_Tolerance_Percent,
        
        /// <remarks/>
        Max_Payment_Tolerance_Amount,
        
        /// <remarks/>
        Payroll_Trans_Import_Format,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void ReadByRecIdCompletedEventHandler(object sender, ReadByRecIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadByRecIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadByRecIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GLSetup Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GLSetup)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void ReadMultipleCompletedEventHandler(object sender, ReadMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GLSetup[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GLSetup[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void IsUpdatedCompletedEventHandler(object sender, IsUpdatedCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsUpdatedCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsUpdatedCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetRecIdFromKeyCompletedEventHandler(object sender, GetRecIdFromKeyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetRecIdFromKeyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetRecIdFromKeyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void UpdateCompletedEventHandler(object sender, UpdateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GLSetup GLSetup {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GLSetup)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void UpdateMultipleCompletedEventHandler(object sender, UpdateMultipleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateMultipleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateMultipleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GLSetup[] GLSetup_List {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GLSetup[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591